"""add roles

Revision ID: 835a1164988b
Revises: b0cc2a37fb87
Create Date: 2022-07-12 10:09:01.960140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835a1164988b'
down_revision = 'b0cc2a37fb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
